# Generated by Django 5.0.6 on 2024-07-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=100, verbose_name='NAME')),
                ('description', models.TextField(blank=True, help_text='simple description text.', verbose_name='DESCRIPTION')),
                ('base_price', models.IntegerField(verbose_name='BASE PRICE')),
                ('additional_price', models.IntegerField(verbose_name='ADDITIONAL PRICE')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
            ],
        ),
        migrations.RemoveField(
            model_name='keepingservice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='keepingservice',
            name='base_service_period',
        ),
        migrations.AddField(
            model_name='keepingservice',
            name='description',
            field=models.TextField(blank=True, help_text='simple description text.', verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='keepingservice',
            name='name',
            field=models.CharField(default='default_name', max_length=100, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='keepingservice',
            name='additional_price',
            field=models.IntegerField(verbose_name='ADDITIONAL PRICE'),
        ),
        migrations.AlterField(
            model_name='keepingservice',
            name='base_price',
            field=models.IntegerField(verbose_name='BASE PRICE'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
