# Generated by Django 5.0.6 on 2024-07-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='keeping_service',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lending_service',
        ),
        migrations.AddField(
            model_name='users',
            name='end_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='keeping_services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='lending_services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='start_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
