# Generated by Django 5.0.6 on 2024-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_users_options_remove_users_keeping_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='keeping_quantities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='users',
            name='lending_quantities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='users',
            name='keeping_services',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='lending_services',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
