# Generated by Django 5.0.6 on 2024-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_users_keeping_quantities_users_lending_quantities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='payment_method',
            field=models.CharField(default='', max_length=5),
        ),
    ]
