# Generated by Django 5.0.6 on 2024-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_users_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='payment_method',
            field=models.CharField(default='', max_length=15),
        ),
    ]
