# Generated by Django 5.0.6 on 2024-08-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_users_final_verification_users_initial_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='chang_status',
            field=models.BooleanField(default=False, verbose_name='변경여부'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
