# Generated by Django 5.0.6 on 2024-09-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_chang_status_users_change_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepingservice',
            name='image_url',
            field=models.TextField(blank=True, help_text='image urls', verbose_name='IMAGE URL'),
        ),
        migrations.AddField(
            model_name='lendingservice',
            name='image_url',
            field=models.TextField(blank=True, help_text='image urls', verbose_name='IMAGE URL'),
        ),
    ]
