# Generated by Django 5.0.6 on 2024-09-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_keepingservice_image_url_lendingservice_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keepingservice',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='lendingservice',
            name='image_url',
        ),
        migrations.AddField(
            model_name='keepingservice',
            name='detail_image',
            field=models.ImageField(blank=True, help_text='Upload the detail image for the service.', upload_to='images/keeping_services/detail/'),
        ),
        migrations.AddField(
            model_name='keepingservice',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Upload the main image for the service.', upload_to='images/keeping_services/main/'),
        ),
        migrations.AddField(
            model_name='lendingservice',
            name='detail_image',
            field=models.ImageField(blank=True, help_text='Upload the detail image for the service.', upload_to='images/lending_services/detail/'),
        ),
        migrations.AddField(
            model_name='lendingservice',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Upload the main image for the service.', upload_to='images/lending_services/main/'),
        ),
    ]
