# Generated by Django 5.0.6 on 2024-08-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
